namespace: default
replicaCount: 1
nameOverride: ''
fullnameOverride: ''

global:
  version: "1.3.8"
  namespace: default
  images:
    hub: dispeakble/crm-hub:1648581007
    db: dispeakble/crm-db:1648581007
    proxy: dispeakble/crm-proxy:1648581007
    frontendproxy: dispeakble/crm-frontend-proxy:1648581007
    frontendapi: dispeakble/crm-frontend-api:1648581007
    system: dispeakble/crm-system:1648581007
    bucket: dispeakble/crm-bucket:1648581007
  env: "local"
  app: "marioviajes"
  redis:
    port: "6379"
    host: "redis-master"
  redis_headless:
    port: "6379"
    host: "redis-headless"
  db:
    name: "main"
    host: "postgresql-ha-pgpool"
    user: "cms"
    password: "0MG9DtWxT@t89*6"
    connections: "main,agency"
  proxy:
    ports:
      admin: "9696"
      public: "9797"