<namespace: default
replicaCount: 1
nameOverride: ''
fullnameOverride: ''

global:
  version: "1.3.2"
  namespace: default
  images:
    hub: dispeakble/crm-hub:1643406843
    db: dispeakble/crm-db:1643406843
    proxy: dispeakble/crm-proxy:1643406843
    frontendproxy: dispeakble/crm-frontend-proxy:1643406843
    frontendapi: dispeakble/crm-frontend-api:1643406843
    system: dispeakble/crm-system:1643406843
    bucket: dispeakble/crm-bucket:1643406843
  env: "local"
  redis:
    port: "6379"
    host: "redis-master"
  redis_headless:
    port: "6379"
    host: "redis-headless"
  db:
    name: "cms"
    host: "postgresql-ha-pgpool"
    user: "cms"
    password: "0MG9DtWxT@t89*6"
  proxy:
    ports:
      admin: "9696"
      public: "9797"