---
apiVersion: v1
data:
  tls.crt: "-----BEGIN CERTIFICATE-----
MIIGNzCCBR+gAwIBAgIRAOzTMY+zjQ85a3O+nRQ1GSIwDQYJKoZIhvcNAQELBQAw
gY8xCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAO
BgNVBAcTB1NhbGZvcmQxGDAWBgNVBAoTD1NlY3RpZ28gTGltaXRlZDE3MDUGA1UE
AxMuU2VjdGlnbyBSU0EgRG9tYWluIFZhbGlkYXRpb24gU2VjdXJlIFNlcnZlciBD
QTAeFw0yMTA4MTMwMDAwMDBaFw0yMjA4MTMyMzU5NTlaMBoxGDAWBgNVBAMMDyou
ZG9zaWRvd2ViLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJtR
fOfvyLsV0VP67xZ5VIr9vT1mDBkqeUykMF6NaurOZ1V8+qfCV60QD1aQ4j2uWuFP
jW4WCRSAfUTAmpIXviC2w87BlAhbfCMN7hR/plwzmlwA5pVURykqmR3ElagsOH+B
Q+h4U3sePY7rIRrA4A+MAkS/wtt7ALaqXL53Ao1+uXqQRM41a+qmifNYD3Rfiqs0
j2OGPG4cZs6N/LZXyq7ge+0LBldDIRwj8HVu5ziGFnFAKP/+GoPjEJNV8247iYDU
qvv8v0aLGo8l2t4P/4S5BRtk7X6fA3/ccjOphs0XlWRoRRYk+Lp4U9ILyYk1cBVs
B2HubkOKLBzbvIb+p/cCAwEAAaOCAwAwggL8MB8GA1UdIwQYMBaAFI2MXsRUrYrh
d+mb+ZsF4bgBjWHhMB0GA1UdDgQWBBTrAnqgGs3KrUeUhF5m+xGgU7LXDDAOBgNV
HQ8BAf8EBAMCBaAwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYI
KwYBBQUHAwIwSQYDVR0gBEIwQDA0BgsrBgEEAbIxAQICBzAlMCMGCCsGAQUFBwIB
FhdodHRwczovL3NlY3RpZ28uY29tL0NQUzAIBgZngQwBAgEwgYQGCCsGAQUFBwEB
BHgwdjBPBggrBgEFBQcwAoZDaHR0cDovL2NydC5zZWN0aWdvLmNvbS9TZWN0aWdv
UlNBRG9tYWluVmFsaWRhdGlvblNlY3VyZVNlcnZlckNBLmNydDAjBggrBgEFBQcw
AYYXaHR0cDovL29jc3Auc2VjdGlnby5jb20wKQYDVR0RBCIwIIIPKi5kb3NpZG93
ZWIuY29tgg1kb3NpZG93ZWIuY29tMIIBfgYKKwYBBAHWeQIEAgSCAW4EggFqAWgA
dgBGpVXrdfqRIDC1oolp9PN9ESxBdL79SbiFq/L8cP5tRwAAAXvCs0UkAAAEAwBH
MEUCICLgHd2tUc/J6dg+jSTx2zgzEpg4KwRnDi9+cktIv0BtAiEAule7C6cs8un6
KiJSQLGpmeCJloCcmuPGzZnPI7GKOOQAdgBByMqx3yJGShDGoToJQodeTjGLGwPr
60vHaPCQYpYG9gAAAXvCs0TnAAAEAwBHMEUCIQCdItRIp0xwMKZzd+8t91S1JmZr
eFRe5s/O2aFduWHqBgIgQlHEuG/xO+6JI1saUjZusINa2RPBqNbga6+ePZfyh/wA
dgApeb7wnjk5IfBWc59jpXflvld9nGAK+PlNXSZcJV3HhAAAAXvCs0S+AAAEAwBH
MEUCIQD2RUEoCWRUM84/tu8urmmEnQYIr8mzSO0wuu0pSTNNdgIgHrWWGtOi7A9d
tTh14XeoTMl2YMYVymuBT67GYsqB8RswDQYJKoZIhvcNAQELBQADggEBAA4+DhAd
FVoQBaS0RefFOhZGezdullu4arM1/ffmwyoGZ4S31AT0a0kVzu9vOSgxbBzToQ+E
J3i5OiWjfsmy3ADVDDDLxHn9O5atYjklIEwK5mmP4rPw086PVk3uRZVjol3qFjaM
/BeFdQiIYTWnp5Iy1AWsb8s+0Zt0rloFupisLHOCISTZdVu7DaeDl7OL6aOqpiVX
V4LAGxG5EwssSjfjM49/6lOzOcVibJnqxJTy4B8Sb+KlT88juXfZ17kMfccH0EuB
kbJJ0FgtMq02xDtSoTK7fsvpRHZtVaa7HofLpHLgfC4QPemUyeJ9hYsj+JiQ/URm
IZhrUkIpQmxapVk=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIFgTCCBGmgAwIBAgIQOXJEOvkit1HX02wQ3TE1lTANBgkqhkiG9w0BAQwFADB7
MQswCQYDVQQGEwJHQjEbMBkGA1UECAwSR3JlYXRlciBNYW5jaGVzdGVyMRAwDgYD
VQQHDAdTYWxmb3JkMRowGAYDVQQKDBFDb21vZG8gQ0EgTGltaXRlZDEhMB8GA1UE
AwwYQUFBIENlcnRpZmljYXRlIFNlcnZpY2VzMB4XDTE5MDMxMjAwMDAwMFoXDTI4
MTIzMTIzNTk1OVowgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpOZXcgSmVyc2V5
MRQwEgYDVQQHEwtKZXJzZXkgQ2l0eTEeMBwGA1UEChMVVGhlIFVTRVJUUlVTVCBO
ZXR3b3JrMS4wLAYDVQQDEyVVU0VSVHJ1c3QgUlNBIENlcnRpZmljYXRpb24gQXV0
aG9yaXR5MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAgBJlFzYOw9sI
s9CsVw127c0n00ytUINh4qogTQktZAnczomfzD2p7PbPwdzx07HWezcoEStH2jnG
vDoZtF+mvX2do2NCtnbyqTsrkfjib9DsFiCQCT7i6HTJGLSR1GJk23+jBvGIGGqQ
Ijy8/hPwhxR79uQfjtTkUcYRZ0YIUcuGFFQ/vDP+fmyc/xadGL1RjjWmp2bIcmfb
IWax1Jt4A8BQOujM8Ny8nkz+rwWWNR9XWrf/zvk9tyy29lTdyOcSOk2uTIq3XJq0
tyA9yn8iNK5+O2hmAUTnAU5GU5szYPeUvlM3kHND8zLDU+/bqv50TmnHa4xgk97E
xwzf4TKuzJM7UXiVZ4vuPVb+DNBpDxsP8yUmazNt925H+nND5X4OpWaxKXwyhGNV
icQNwZNUMBkTrNN9N6frXTpsNVzbQdcS2qlJC9/YgIoJk2KOtWbPJYjNhLixP6Q5
D9kCnusSTJV882sFqV4Wg8y4Z+LoE53MW4LTTLPtW//e5XOsIzstAL81VXQJSdhJ
WBp/kjbmUZIO8yZ9HE0XvMnsQybQv0FfQKlERPSZ51eHnlAfV1SoPv10Yy+xUGUJ
5lhCLkMaTLTwJUdZ+gQek9QmRkpQgbLevni3/GcV4clXhB4PY9bpYrrWX1Uu6lzG
KAgEJTm4Diup8kyXHAc/DVL17e8vgg8CAwEAAaOB8jCB7zAfBgNVHSMEGDAWgBSg
EQojPpbxB+zirynvgqV/0DCktDAdBgNVHQ4EFgQUU3m/WqorSs9UgOHYm8Cd8rID
ZsswDgYDVR0PAQH/BAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wEQYDVR0gBAowCDAG
BgRVHSAAMEMGA1UdHwQ8MDowOKA2oDSGMmh0dHA6Ly9jcmwuY29tb2RvY2EuY29t
L0FBQUNlcnRpZmljYXRlU2VydmljZXMuY3JsMDQGCCsGAQUFBwEBBCgwJjAkBggr
BgEFBQcwAYYYaHR0cDovL29jc3AuY29tb2RvY2EuY29tMA0GCSqGSIb3DQEBDAUA
A4IBAQAYh1HcdCE9nIrgJ7cz0C7M7PDmy14R3iJvm3WOnnL+5Nb+qh+cli3vA0p+
rvSNb3I8QzvAP+u431yqqcau8vzY7qN7Q/aGNnwU4M309z/+3ri0ivCRlv79Q2R+
/czSAaF9ffgZGclCKxO/WIu6pKJmBHaIkU4MiRTOok3JMrO66BQavHHxW/BBC5gA
CiIDEOUMsfnNkjcZ7Tvx5Dq2+UUTJnWvu6rvP3t3O9LEApE9GQDTF1w52z97GA1F
zZOFli9d31kWTz9RvdVFGD/tSo7oBmF0Ixa1DVBzJ0RHfxBdiSprhTEUxOipakyA
vGp4z7h/jnZymQyd/teRCBaho1+V
-----END CERTIFICATE-----"
  tls.key: "-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEAm1F85+/IuxXRU/rvFnlUiv29PWYMGSp5TKQwXo1q6s5nVXz6
p8JXrRAPVpDiPa5a4U+NbhYJFIB9RMCakhe+ILbDzsGUCFt8Iw3uFH+mXDOaXADm
lVRHKSqZHcSVqCw4f4FD6HhTex49jushGsDgD4wCRL/C23sAtqpcvncCjX65epBE
zjVr6qaJ81gPdF+KqzSPY4Y8bhxmzo38tlfKruB77QsGV0MhHCPwdW7nOIYWcUAo
//4ag+MQk1XzbjuJgNSq+/y/RosajyXa3g//hLkFG2Ttfp8Df9xyM6mGzReVZGhF
FiT4unhT0gvJiTVwFWwHYe5uQ4osHNu8hv6n9wIDAQABAoIBAFoKdpfbKYpTzqOZ
4Ist0XY2PUPf6fmY5vMoaCYYY7g16i/kIUep4bwhiFLN8WqCrorZ3IrKWX86MeTu
p200OHOsoH03OcNSjfegdroJen8PJ1hY6VP+pLZXzKY2NfBlmmdIn/6f6v1//X3i
D7H7yKkaqKIEbUlh2HsM7nE4exFdU6TLuS1PzV1RNeiuRhLmKfc5Kjc2SZwuUHwS
bpZP23R3ItK3LzxXZLfwDMagmWe/UMmFOztUKYfY5eJ91ai/jS/VdDWKFLQtb7oz
7tI59faIg8BZtKt48lx0gOCLyCznIDcfJaC0SLRvhA0uMXPQeZZL7+vcdcF9kU13
ujBUTskCgYEAx2e92kMOef33doeKnuK7WjAhMwbiJuT9rE2P9pwh5AegqzgFWlGC
KH67+34gWwY5pN3J19hLHBlrnZ4DWOhCNuAev2fG/30o2On4ejGbpUp57yoVXKzL
r6R2u6hvuyVJqlYP3fNum4I2sNwGjcOyCz6kM3WaW66Zm1GYCUL6rtUCgYEAx2aB
p1kIzsjd+mdAyKzH4Auv/4B2xY7jaloNr3j6i/oMsr5tsCY9l3MQxlc21FGO9xQq
is1mRKkMCgDXBrFOG8b1Wi2KMig6Zrvrqu0fETeRdPUN2VqZArUjrzE4gquya1WA
98NIDxfz2U5Cv3eijgmDyrvYZ4W8haRplz+UGZsCgYEAnukp/7rY2pdukuNJsX13
WVRp4MRnjh+HmbzmMd4TlCoP/ONUQLocRDFblfzZxDCd16l4pa8VjHslrCK1ADF4
M0tAtcD6cblIyDUNdDP8milUKykahRSf7oXeqYZ+JGJ+5mRXmMXbK8sF0sRF5MxE
I3n0WZ4rOU1X1NOdmiPqq1ECgYEAn2vQKyjfBtzHxMS6ofaqEvGlM+TUkNzN66C2
Il3aCwHPFzVy4wuf4K8pcToXZycR428nGDRiGHEDZBgJ0pr9dO3cCc4xGCrbjnme
UNkmJpDD5btq6CUsAmMqdY4nvSljC7ef1fc2bILc/hc4/HW87EylJviKazIcaMjr
dvZpBRMCgYEApKGz5CsjPY7l4by67lEyA+5Js0iOeHpHJka2lTDcQwlAPyYFNsaY
6PgKURFWdOMqiVSgLCHbtSA9rPi+RGzk6zBTs3i6m2C9cGI0utwHJRuhqoVXDfpV
w/4L46AQTlVhZ1dR26sWNOUhoHAfyuddZNyBlWO+YmSt+xtXNnEXsjc=
-----END RSA PRIVATE KEY-----"
kind: Secret
metadata:
  name: dosidowebcom
  namespace: default
type: kubernetes.io/tls

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  generation: 1
  labels:
    cattle.io/creator: norman
  managedFields:
    - apiVersion: extensions/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/creatorId: {}
            f:field.cattle.io/ingressState: {}
          f:labels:
            .: {}
            f:cattle.io/creator: {}
        f:spec:
          f:rules: {}
          f:tls: {}
      manager: rancher
      operation: Update
  name: frontend-lb
  namespace: default
  resourceVersion: "5921"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/frontend-lb
spec:
  rules:
    - host: dosidoweb.com
      http:
        paths:
          - backend:
              serviceName: frontend-api-proxy
              servicePort: 9797
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - dosidoweb.com
      secretName: dosidowebcom
status:
  loadBalancer: {}

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/ingressState: '{"YWRtaW4tbGIvZGVmYXVsdC9hZG1pbi5kb3NpZG93ZWIuY29tLy85Njk2":"","ZG9zaWRvd2ViY29t":"p-c5cmv:dosidowebcom"}'
  generation: 1
  labels:
    cattle.io/creator: norman
  managedFields:
    - apiVersion: extensions/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/creatorId: {}
            f:field.cattle.io/ingressState: {}
          f:labels:
            .: {}
            f:cattle.io/creator: {}
        f:spec:
          f:rules: {}
          f:tls: {}
      manager: rancher
      operation: Update
  name: admin-lb
  namespace: default
  resourceVersion: "9913"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/admin-lb
spec:
  rules:
    - host: admin.dosidoweb.com
      http:
        paths:
          - backend:
              serviceName: admin-service
              servicePort: 9696
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - admin.dosidoweb.com
      secretName: dosidowebcom
status:
  loadBalancer: {}
