apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/creatorId: user-p4fvq
    field.cattle.io/ipAddresses: "null"
    field.cattle.io/targetDnsRecordIds: "null"
    field.cattle.io/targetWorkloadIds: "null"
  creationTimestamp: "2021-07-16T17:58:35Z"
  labels:
    cattle.io/creator: norman
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/creatorId: {}
            f:field.cattle.io/ipAddresses: {}
            f:field.cattle.io/targetDnsRecordIds: {}
            f:field.cattle.io/targetWorkloadIds: {}
          f:labels:
            .: {}
            f:cattle.io/creator: {}
        f:spec:
          f:clusterIP: {}
          f:ports:
            .: {}
            k:{"port":9696,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector:
            .: {}
            f:app: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: rancher
      operation: Update
      time: "2021-07-16T17:58:35Z"
  name: cms-proxy-backend-mlb
  namespace: default
  resourceVersion: "134891"
  selfLink: /api/v1/namespaces/default/services/cms-proxy-backend-mlb
  uid: 70442425-22f9-4ff0-a6da-24d3af5a9fb5
spec:
  clusterIP: None
  ports:
    - name: backend
      port: 9696
      protocol: TCP
      targetPort: 9696
  selector:
    app: cms-proxy-backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}