#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: cms-local-proxy
#  namespace: default
#spec:
#  clusterIP: None
#  ports:
#    - name: admin
#      port: 9696
#      protocol: TCP
#      targetPort: 9696
#  selector:
#    app: cms-proxy
#  sessionAffinity: None
#  type: ClusterIP
