#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: fakeclient.com
#  namespace: default
#spec:
#  rules:
#    - host: fakeclient.com
#      http:
#        paths:
#          - frontend:
#              serviceName: cms-proxy-service
#              servicePort: 9797
#            path: /
#            pathType: ImplementationSpecific
#status:
#  loadBalancer: {}