apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/creatorId: user-p4fvq
    field.cattle.io/ipAddresses: "null"
    field.cattle.io/targetDnsRecordIds: "null"
    field.cattle.io/targetWorkloadIds: "null"
  creationTimestamp: "2021-07-16T07:51:36Z"
  labels:
    cattle.io/creator: norman
    service: cms-backend
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/creatorId: {}
            f:field.cattle.io/ipAddresses: {}
            f:field.cattle.io/targetDnsRecordIds: {}
            f:field.cattle.io/targetWorkloadIds: {}
          f:labels:
            .: {}
            f:cattle.io/creator: {}
            f:service: {}
        f:spec:
          f:ports:
            .: {}
            k:{"port":9797,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector:
            .: {}
            f:app: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: rancher
      operation: Update
      time: "2021-07-16T07:51:36Z"
  name: cms-proxy-frontend-service
  namespace: default
  resourceVersion: "11476"
  selfLink: /api/v1/namespaces/default/services/cms-proxy-frontend-service
spec:
  clusterIP: 10.43.97.22
  ports:
    - name: frontent
      port: 9797
      protocol: TCP
      targetPort: 9797
  selector:
    app: cms-proxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
