apiVersion: v1
kind: Service
metadata:
  name: cms-proxy-service
  namespace: default
spec:
  clusterIP: None
  ports:
    - name: backend
      port: 9696
      protocol: TCP
      targetPort: 9696
    - name: frontend
      port: 9797
      protocol: TCP
      targetPort: 9797
  selector:
    app: cms-proxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}