namespace: default
replicaCount: 1
nameOverride: ''
fullnameOverride: ''

global:
  version: "0.1.0"
  namespace: default
  images:
    hub: dispeakble/crm-hub:1629223556
    db: dispeakble/crm-db:1629223556
    proxy: dispeakble/crm-proxy:1629223556
    frontendproxy: dispeakble/crm-frontend-proxy:1629223556
    frontendapi: dispeakble/crm-frontend-api:1629223556
    system: dispeakble/crm-system:1629223556
    bucket: dispeakble/crm-bucket:1629223556
  env: "local"
  redis:
    port: "6379"
    host: "redis-cluster-headless"
  db:
    name: "cms"
    host: "postgresql-ha-pgpool"
    user: "cms"
    password: "0MG9DtWxT@t89*6"
  proxy:
    ports:
      admin: "9696"
      public: "9797"