namespace: default
replicaCount: 1
nameOverride: ''
fullnameOverride: ''

global:
  version: "0.1.0"
  namespace: default
  images:
    hub: dispeakble/crm-hub:1626251436
    db: dispeakble/crm-db:1626251436
    proxy: dispeakble/crm-proxy:1626251436
    system: dispeakble/crm-system:1626251436
    bucket: dispeakble/crm-bucket:1626251436
  env: "local"
  redis:
    port: "6379"
    host: "redis-master"
  db:
    name: "cms"
    host: "postgresql-ha-pgpool"
    user: "cms"
    password: "0MG9DtWxT@t89*6"
  proxy:
    ports:
      admin: "9696"
      public: "9797"