apiVersion: v2
appVersion: 1.6.3
description: Install Hub
icon: https://as2.ftcdn.net/v2/jpg/03/78/06/07/1000_F_378060747_6Z3pohk90HAcfbGog7X1DizBU7NCQeqM.jpg
name: cms-hub
type: application
version: 1.6.3

dependencies:
  - name: redis
    condition: redis.enabled