apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-cms-bucket
  name: cms-bucket
  namespace: {{ .Values.namespace }}
  selfLink: /apis/apps/v1/namespaces/default/deployments/cms-bucket
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-cms-bucket
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-cms-bucket
    spec:
      containers:
        - env:
          - name: redis_port
            value: "{{ .Values.global.redis-headless.port }}"
          - name: redis_server
            value: "{{ .Values.global.redis-headless.host }}"
          - name: redis_password
            valueFrom:
              secretKeyRef:
                key: redis-password
                name: redis-cluster
                optional: false
          image: {{ .Values.global.images.bucket }}
          imagePullPolicy: IfNotPresent
          name: cms-bucket
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: "/usr/src/api/var"
              name: bucket-pv-storage
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: dockerhub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: bucket-pv-storage
          persistentVolumeClaim:
            claimName: bucket-pv-claim
status: {}
