apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 2
  labels:
    workload.user.cattle.io/workloadselector: deployment-default-cms-frontend-api
  name: cms-frontend-api
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-cms-frontend-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cms-frontend-api
        workload.user.cattle.io/workloadselector: deployment-default-cms-frontend-api
    spec:
      containers:
        - env:
          - name: app
            value: "{{ .Values.global.app.name }}"
          - name: website_domain
            value: "{{ .Values.global.app.website.domain }}"
          - name: tpl_ver
            value: "{{ .Values.global.app.website.tpl_ver }}"
          - name: backend_port
            value: "{{ .Values.global.proxy.ports.public }}"
          - name: redis_server
            value: "{{ .Values.global.redis.host }}"
          - name: redis_port
            value: "{{ .Values.global.redis.port }}"
          - name: redis_password
            value: "{{ .Values.global.redis.password }}"
          - name: NODE_ENV
            value: "production"
          - name: recaptcha_public_key
            value: "{{ .Values.global.app.secrets.recaptcha_public_key }}"
          - name: recaptcha_private_key
            value: "{{ .Values.global.app.secrets.recaptcha_private_key }}"
          image: {{ .Values.global.images.frontendapi }}
          imagePullPolicy: IfNotPresent
          name: cms-frontend-api
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: dockerhub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
