apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/ipAddresses: "null"
    field.cattle.io/targetDnsRecordIds: "null"
    field.cattle.io/targetWorkloadIds: '["deployment:default:cms-frontend-api"]'
  creationTimestamp: "2021-10-11T08:37:45Z"
  labels:
    cattle.io/creator: norman
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:selector:
            .: {}
            f:workloadID_frontend-service: {}
      manager: Go-http-client
      operation: Update
      time: "2021-10-11T08:37:45Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/creatorId: {}
            f:field.cattle.io/ipAddresses: {}
            f:field.cattle.io/targetDnsRecordIds: {}
            f:field.cattle.io/targetWorkloadIds: {}
          f:labels:
            .: {}
            f:cattle.io/creator: {}
        f:spec:
          f:ports:
            .: {}
            k:{"port":9797,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: rancher
      operation: Update
      time: "2021-10-11T08:37:45Z"
  name: frontend-service
  namespace: default
  resourceVersion: "3668707"
  selfLink: /api/v1/namespaces/default/services/frontend-service
spec:
  ports:
    - name: frontendport
      port: 9797
      protocol: TCP
      targetPort: 9797
  selector:
    workloadID_frontend-service: "true"
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  generation: 1
  labels:
    cattle.io/creator: norman
  managedFields:
    - apiVersion: extensions/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/creatorId: {}
            f:field.cattle.io/ingressState: {}
          f:labels:
            .: {}
            f:cattle.io/creator: {}
        f:spec:
          f:rules: {}
          f:tls: {}
      manager: rancher
      operation: Update
  name: frontend-lb
  namespace: default
  resourceVersion: "5921"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/frontend-lb
spec:
  rules:
    - host: dosidoweb.com
      http:
        paths:
          - backend:
              serviceName: frontend-service
              servicePort: 9797
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - dosidoweb.com
      secretName: dosidowebcom
status:
  loadBalancer: {}
