apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/creatorId: user-57kzm
    field.cattle.io/ipAddresses: "null"
    field.cattle.io/targetDnsRecordIds: "null"
    field.cattle.io/targetWorkloadIds: "null"
  labels:
    cattle.io/creator: norman
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:clusterIP: {}
          f:ports:
            .: {}
            k:{"port":9797,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector:
            .: {}
            f:app: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: rancher
      operation: Update
  name: frontend-service
spec:
  clusterIP: None
  ports:
    - name: frontend-proxy
      port: 9797
      protocol: TCP
      targetPort: 9797
  selector:
    app: cms-frontend-proxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}


---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  generation: 1
  labels:
    cattle.io/creator: norman
  managedFields:
    - apiVersion: networking.k8s.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:loadBalancer:
            f:ingress: {}
      manager: nginx-ingress-controller
      operation: Update
    - apiVersion: extensions/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/creatorId: {}
            f:field.cattle.io/ingressState: {}
            f:field.cattle.io/publicEndpoints: {}
          f:labels:
            .: {}
            f:cattle.io/creator: {}
        f:spec:
          f:rules: {}
          f:tls: {}
      manager: rancher
      operation: Update
  name: frontend-lb
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/frontend-lb
spec:
  rules:
    - host: dosidoweb.com
      http:
        paths:
          - backend:
              serviceName: frontend-service
              servicePort: 9797
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - dosidoweb.com
      secretName: dosidowebcom
status:
  loadBalancer:
    ingress:
      - ip: 188.214.30.235

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  generation: 1
  labels:
    cattle.io/creator: norman
  managedFields:
    - apiVersion: networking.k8s.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:loadBalancer:
            f:ingress: {}
      manager: nginx-ingress-controller
      operation: Update
    - apiVersion: extensions/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/creatorId: {}
            f:field.cattle.io/ingressState: {}
            f:field.cattle.io/publicEndpoints: {}
          f:labels:
            .: {}
            f:cattle.io/creator: {}
        f:spec:
          f:rules: {}
          f:tls: {}
      manager: rancher
      operation: Update
  name: wwwfrontend-lb
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/wwwfrontend-lb
spec:
  rules:
    - host: www.dosidoweb.com
      http:
        paths:
          - backend:
              serviceName: frontend-service
              servicePort: 9797
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - www.dosidoweb.com
      secretName: dosidowebcom
status:
  loadBalancer:
    ingress:
      - ip: 188.214.30.235
