apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-cms-proxy
  name: cms-proxy
  namespace: {{ .Values.namespace }}
  selfLink: /apis/apps/v1/namespaces/default/deployments/cms-proxy
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-cms-proxy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cms-proxy
        workload.user.cattle.io/workloadselector: deployment-default-cms-proxy
    spec:
      containers:
        - env:
          - name: app
            value: "{{ .Values.global.app.name }}"
          - name: backend_port
            value: "{{ .Values.global.proxy.ports.admin }}"
          - name: redis_port
            value: "{{ .Values.global.redis.port }}"
          - name: redis_server
            value: "{{ .Values.global.redis.host }}"
          - name: session_secret
            value: 1qaz
          - name: redis_password
            value: "{{ .Values.global.redis.password }}"
          image: {{ .Values.global.images.proxy }}
          imagePullPolicy: IfNotPresent
          name: cms-proxy
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: dockerhub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
